In [1]:
# Useful additional packages
import matplotlib.pyplot as plt
import numpy as np
from math import pi

In [2]:
from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister, transpile
from qiskit.tools.visualization import circuit_drawer
from qiskit.quantum_info import state_fidelity
from qiskit import BasicAer

backend = BasicAer.get_backend('unitary_simulator')

In [3]:
q = QuantumRegister(1)

In [4]:
qc = QuantumCircuit(q)
qc.u(pi/2,pi/4,pi/8,q)
qc.draw()

┌────────────────┐
q0: ┤ U(π/2,π/4,π/8) ├
    └────────────────┘

In [5]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[ 0.707+0.j   , -0.653-0.271j],
       [ 0.5  +0.5j  ,  0.271+0.653j]])

In [6]:
qc = QuantumCircuit(q)
qc.p(pi/2,q)
qc.draw()

┌────────┐
q0: ┤ P(π/2) ├
    └────────┘

In [7]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 0.+1.j]])

In [8]:
qc = QuantumCircuit(q)
qc.id(q)
qc.draw()

┌───┐
q0: ┤ I ├
    └───┘

In [9]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]])

In [10]:
qc = QuantumCircuit(q)
qc.x(q)
qc.draw()

┌───┐
q0: ┤ X ├
    └───┘

In [11]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[0.+0.j, 1.+0.j],
       [1.+0.j, 0.+0.j]])

In [12]:
qc = QuantumCircuit(q)
qc.y(q)
qc.draw()

┌───┐
q0: ┤ Y ├
    └───┘

In [13]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[ 0.+0.j, -0.-1.j],
       [ 0.+1.j,  0.+0.j]])

In [14]:
qc = QuantumCircuit(q)
qc.z(q)
qc.draw()

┌───┐
q0: ┤ Z ├
    └───┘

In [15]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[ 1.+0.j,  0.+0.j],
       [ 0.+0.j, -1.+0.j]])

In [16]:
qc = QuantumCircuit(q)
qc.h(q)
qc.draw()

┌───┐
q0: ┤ H ├
    └───┘

In [17]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[ 0.707+0.j,  0.707-0.j],
       [ 0.707+0.j, -0.707+0.j]])

In [18]:
qc = QuantumCircuit(q)
qc.s(q)
qc.draw()

┌───┐
q0: ┤ S ├
    └───┘

In [19]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 0.+1.j]])

In [20]:
qc = QuantumCircuit(q)
qc.sdg(q)
qc.draw()

┌─────┐
q0: ┤ Sdg ├
    └─────┘

In [21]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 0.-1.j]])

In [22]:
qc = QuantumCircuit(q)
qc.t(q)
qc.draw()

┌───┐
q0: ┤ T ├
    └───┘

In [23]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[1.   +0.j   , 0.   +0.j   ],
       [0.   +0.j   , 0.707+0.707j]])

In [24]:
qc = QuantumCircuit(q)
qc.tdg(q)
qc.draw()

┌─────┐
q0: ┤ Tdg ├
    └─────┘

In [25]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[1.   +0.j   , 0.   +0.j   ],
       [0.   +0.j   , 0.707-0.707j]])

In [26]:
qc = QuantumCircuit(q)
qc.rx(pi/2,q)
qc.draw()

┌─────────┐
q0: ┤ Rx(π/2) ├
    └─────────┘

In [27]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[ 0.707+0.j   , -0.   -0.707j],
       [ 0.   -0.707j,  0.707+0.j   ]])

In [28]:
qc = QuantumCircuit(q)
qc.ry(pi/2,q)
qc.draw()

┌─────────┐
q0: ┤ Ry(π/2) ├
    └─────────┘

In [29]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[ 0.707+0.j, -0.707+0.j],
       [ 0.707+0.j,  0.707+0.j]])

In [30]:
qc = QuantumCircuit(q)
qc.rz(pi/2,q)
qc.draw()

┌─────────┐
q0: ┤ Rz(π/2) ├
    └─────────┘

In [31]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[0.707-0.707j, 0.   +0.j   ],
       [0.   +0.j   , 0.707+0.707j]])

In [32]:
q = QuantumRegister(2)

In [33]:
qc = QuantumCircuit(q)
qc.cx(q[0],q[1])
qc.draw()

q15_0: ──■──
       ┌─┴─┐
q15_1: ┤ X ├
       └───┘

In [34]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j]])

In [35]:
qc = QuantumCircuit(q)
qc.cy(q[0],q[1])
qc.draw()

q15_0: ──■──
       ┌─┴─┐
q15_1: ┤ Y ├
       └───┘

In [36]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.-1.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j]])

In [37]:
qc = QuantumCircuit(q)
qc.cz(q[0],q[1])
qc.draw()

q15_0: ─■─
        │ 
q15_1: ─■─

In [38]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[ 1.-0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  1.-0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  1.-0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j, -1.+0.j]])

In [39]:
qc = QuantumCircuit(q)
qc.ch(q[0],q[1])
qc.draw()

q15_0: ──■──
       ┌─┴─┐
q15_1: ┤ H ├
       └───┘

In [40]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[ 1.   +0.j,  0.   +0.j,  0.   +0.j,  0.   +0.j],
       [ 0.   +0.j,  0.707+0.j,  0.   +0.j,  0.707-0.j],
       [ 0.   +0.j,  0.   +0.j,  1.   -0.j,  0.   +0.j],
       [ 0.   +0.j,  0.707+0.j,  0.   +0.j, -0.707+0.j]])

In [41]:
qc = QuantumCircuit(q)
qc.crz(pi/2,q[0],q[1])
qc.draw()

q15_0: ─────■─────
       ┌────┴────┐
q15_1: ┤ Rz(π/2) ├
       └─────────┘

In [42]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[1.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   ],
       [0.   +0.j   , 0.707-0.707j, 0.   +0.j   , 0.   +0.j   ],
       [0.   +0.j   , 0.   +0.j   , 1.   +0.j   , 0.   +0.j   ],
       [0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.707+0.707j]])

In [43]:
qc = QuantumCircuit(q)
qc.cp(pi/2,q[0], q[1])
qc.draw()

q15_0: ─■───────
        │P(π/2) 
q15_1: ─■───────

In [44]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+1.j]])

In [45]:
qc = QuantumCircuit(q)
qc.cu(pi/2, pi/2, pi/2, 0, q[0], q[1])
qc.draw()

q15_0: ─────────■──────────
       ┌────────┴─────────┐
q15_1: ┤ U(π/2,π/2,π/2,0) ├
       └──────────────────┘

In [46]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[ 1.   +0.j   ,  0.   +0.j   ,  0.   +0.j   ,  0.   +0.j   ],
       [ 0.   +0.j   ,  0.707+0.j   ,  0.   +0.j   , -0.   -0.707j],
       [ 0.   +0.j   ,  0.   +0.j   ,  1.   +0.j   ,  0.   +0.j   ],
       [ 0.   +0.j   ,  0.   +0.707j,  0.   +0.j   , -0.707+0.j   ]])

In [47]:
qc = QuantumCircuit(q)
qc.swap(q[0], q[1])
qc.draw()

q15_0: ─X─
        │ 
q15_1: ─X─

In [48]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [49]:
q = QuantumRegister(3)

In [50]:
qc = QuantumCircuit(q)
qc.ccx(q[0], q[1], q[2])
qc.draw()

q24_0: ──■──
         │  
q24_1: ──■──
       ┌─┴─┐
q24_2: ┤ X ├
       └───┘

In [51]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.-0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.-0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.-0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.-0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [52]:
qc = QuantumCircuit(q)
qc.cswap(q[0], q[1], q[2])
qc.draw()

q24_0: ─■─
        │ 
q24_1: ─X─
        │ 
q24_2: ─X─

In [53]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.-0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.-0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.-0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.-0.j]])

In [54]:
q = QuantumRegister(1)
c = ClassicalRegister(1)

In [55]:
qc = QuantumCircuit(q, c)
qc.measure(q, c)
qc.draw()

┌─┐
 q27: ┤M├
      └╥┘
c0: 1/═╩═
       0

In [56]:
backend = BasicAer.get_backend('qasm_simulator')
job = backend.run(transpile(qc, backend))
job.result().get_counts(qc)

{'0': 1024}

In [57]:
qc = QuantumCircuit(q, c)
qc.h(q)
qc.measure(q, c)
qc.draw()

┌───┐┌─┐
 q27: ┤ H ├┤M├
      └───┘└╥┘
c0: 1/══════╩═
            0

In [58]:
job = backend.run(transpile(qc, backend))
job.result().get_counts(qc)

{'0': 484, '1': 540}

In [59]:
qc = QuantumCircuit(q, c)
qc.reset(q[0])
qc.measure(q, c)
qc.draw()

┌─┐
 q27: ─|0>─┤M├
           └╥┘
c0: 1/══════╩═
            0

In [60]:
job = backend.run(transpile(qc, backend))
job.result().get_counts(qc)

{'0': 1024}

In [61]:
qc = QuantumCircuit(q, c)
qc.h(q)
qc.reset(q[0])
qc.measure(q, c)
qc.draw()

┌───┐     ┌─┐
 q27: ┤ H ├─|0>─┤M├
      └───┘     └╥┘
c0: 1/═══════════╩═
                 0

In [62]:
job = backend.run(transpile(qc, backend))
job.result().get_counts(qc)

{'0': 1024}

In [63]:
qc = QuantumCircuit(q, c)
qc.x(q[0]).c_if(c, 0)
qc.measure(q,c)
qc.draw()

┌───┐ ┌─┐
 q27: ─┤ X ├─┤M├
       └─╥─┘ └╥┘
      ┌──╨──┐ ║ 
c0: 1/╡ 0x0 ╞═╩═
      └─────┘ 0

In [64]:
job = backend.run(transpile(qc, backend))
job.result().get_counts(qc)

{'1': 1024}

In [65]:
qc = QuantumCircuit(q, c)
qc.h(q)
qc.measure(q,c)
qc.x(q[0]).c_if(c, 0)
qc.measure(q,c)
qc.draw()

┌───┐┌─┐ ┌───┐ ┌─┐
 q27: ┤ H ├┤M├─┤ X ├─┤M├
      └───┘└╥┘ └─╥─┘ └╥┘
            ║ ┌──╨──┐ ║ 
c0: 1/══════╩═╡ 0x0 ╞═╩═
            0 └─────┘ 0

In [66]:
job = backend.run(transpile(qc, backend))
job.result().get_counts(qc)

{'1': 1024}

In [67]:
# Initializing a three-qubit quantum state
import math
desired_vector = [
    1 / math.sqrt(16) * complex(0, 1),
    1 / math.sqrt(8) * complex(1, 0),
    1 / math.sqrt(16) * complex(1, 1),
    0,
    0,
    1 / math.sqrt(8) * complex(1, 2),
    1 / math.sqrt(16) * complex(1, 0),
    0]


q = QuantumRegister(3)

qc = QuantumCircuit(q)

qc.initialize(desired_vector, [q[0],q[1],q[2]])
qc.draw()

┌───────────────────────────────────────────────────────────────────┐
q41_0: ┤0                                                                  ├
       │                                                                   │
q41_1: ┤1 Initialize(0.25j,0.35355,0.25+0.25j,0,0,0.35355+0.70711j,0.25,0) ├
       │                                                                   │
q41_2: ┤2                                                                  ├
       └───────────────────────────────────────────────────────────────────┘

In [68]:
backend = BasicAer.get_backend('statevector_simulator')
job = backend.run(transpile(qc, backend))
qc_state = job.result().get_statevector(qc)
qc_state

array([1.66533454e-16+2.50000000e-01j, 3.53553391e-01-5.55111512e-17j,
       2.50000000e-01+2.50000000e-01j, 0.00000000e+00+0.00000000e+00j,
       0.00000000e+00+0.00000000e+00j, 3.53553391e-01+7.07106781e-01j,
       2.50000000e-01-9.02056208e-17j, 0.00000000e+00+0.00000000e+00j])

In [69]:
state_fidelity(desired_vector,qc_state)

1.0000000000000004

In [70]:
import qiskit.tools.jupyter
%qiskit_version_table
%qiskit_copyright